apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productA
  annotations:
    "codefresh.io/product": test-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: services-chart
    repoURL: https://github.com/yaroslav-codefresh/scale-test.git
    targetRevision: HEAD
    helm:
      valuesObject:
        product: productA
        runtimeNamespace: productA
        prod:
          repoUrl: https://github.com/oleksandr-codefresh/argo-load-product
          cluster: scale-prod
          path: helm-guestbook
        dev:
          repoUrl: https://github.com/oleksandr-codefresh/argo-load-product
          cluster: scale-test
          path: helm-guestbook
  destination:
    name: in-cluster
    namespace: argo-load
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
