apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: final-apps
    repoURL: https://github.com/yaroslav-codefresh/scale-test.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: gs-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
