apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
#    path: services-chart
#    repoURL: https://github.com/yaroslav-codefresh/scale-test.git
#    targetRevision: HEAD
#    helm:
#      valuesObject:
#        spec:
#          product: asdf
    path: helm-guestbook
    repoURL: https://github.com/yaroslav-codefresh/argocd-example-apps.git
    targetRevision: HEAD
#  destination:
#    name: in-cluster
#    namespace: cf-runtime
  destination:
    name: in-cluster
    namespace: asdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
