apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  annotations:
    "codefresh.io/product": test-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: single-service-chart
    repoURL: https://github.com/yaroslav-codefresh/scale-test.git
    targetRevision: HEAD
    helm:
      valuesObject:
        spec:
          product: test-app
          runtimeNamespace: argo-load
          prod:
            cluster: scale-prod
            path: prod
            repoUrl: https://github.com/oleksandr-codefresh/argo-load-product-1
          dev:
            cluster: scale-test
            path: dev
            repoUrl: https://github.com/oleksandr-codefresh/argo-load-product-1
  destination:
    name: in-cluster
    namespace: argo-load
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
