apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.product }}-service-6
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: apps-chart
    repoURL: https://github.com/yaroslav-codefresh/scale-test.git
    targetRevision: HEAD
    helm:
      valuesObject:
        spec:
          service: service-6
          product: {{ .Values.spec.product }}
  destination:
    name: in-cluster
    namespace: {{ .Values.spec.runtimeNamespace }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
