apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.spec.product }}-appset
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  generators:
    - list:
        elements:
          - appCount: 1
  template:
    metadata:
      name: {{ .Values.spec.product }}-appset-app-{{`{{appCount}}`}}
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
    spec:
      project: default
      source:
        path: helm-guestbook
        repoURL: https://github.com/yaroslav-codefresh/argocd-example-apps.git
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: cf-runtime
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
          - ServerSideApply=true
          - RespectIgnoreDifferences=false
