{
 "title": "Argo Events",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "trigger_name", "label": "trigger_name", "query": { "query": "label_values(trigger_name)" } },
   { "name": "sensor_name", "query": { "query": "label_values(sensor_name)" } },
   { "name": "eventsource_name", "query": { "query": "label_values(eventsource_name)" } },
   { "name": "event_name", "query": { "query": "label_values(event_name)" } }
  ]
 },
 "panels": [
  { "title": "All", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(argo_events_action_duration_milliseconds_sum{job=\"prometheus/argo-events-resources-pod-monitor\", trigger_name=~\"$trigger_name\", sensor_name=~\"$sensor_name\"}[$__rate_interval]) / 1000) / rate(argo_events_action_duration_milliseconds_count[$__rate_interval])",
     "legendFormat": "{{sensor_name}} | {{trigger_name}}"
    }
   ]
  },
  {
   "title": "Throughput Events",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(argo_events_events_sent_total{job=\"prometheus/argo-events-resources-pod-monitor\", event_name=~\"$event_name\", eventsource_name=~\"$eventsource_name\"}[$__rate_interval])",
     "legendFormat": "{{eventsource_name}} | {{event_name}}"
    }
   ]
  },
  {
   "title": "Throughput Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(argo_events_action_triggered_total{job=\"prometheus/argo-events-resources-pod-monitor\", trigger_name=~\"$trigger_name\", sensor_name=~\"$sensor_name\"}[$__rate_interval])",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  }
 ]
}