replicaCount: 4
image:
  repository: xeonalex/guesbook
  tag: "0.4"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
