{
 "title": "Codefresh argo-cd events reporter (v2)",
 "time": { "from": "2024-02-06T22:00:00.000Z", "to": "2024-02-09T21:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "reporter_shard",
    "label": "Shard number",
    "query": {
     "query": "label_values(cf_e_reporter_queue_size,reporter_shard)"
    }
   },
   {
    "name": "metric_event_type",
    "label": "Metric event type",
    "query": {
     "query": "label_values(cf_e_reporter_event_processing_duration_bucket,metric_event_type)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "General stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current queue size",
   "type": "stat",
   "gridPos": { "h": 22, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cf_e_reporter_queue_size{cluster=\"managed-runtimes-production\"}",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Predicted queue size (10 mins)",
   "type": "stat",
   "gridPos": { "h": 22, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "predict_linear(cf_e_reporter_queue_size{cluster=\"managed-runtimes-production\"}[$__interval], 60*10)",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Queue size delta (1m)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cf_e_reporter_queue_size{reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\"}[1m])",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cf_e_reporter_queue_size{reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\", namespace=\"mr-sojern-new-1e325d9-rmp8b\"}",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Events rate limited (real)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cf_e_reporter_app_events_size{reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\", namespace=\"mr-sojern-new-1e325d9-rmp8b\", got_in_queue=\"false\"}[$__rate_interval])",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Events rate limited (learning)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cf_e_reporter_app_events_size{reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\", namespace=\"mr-sojern-new-1e325d9-rmp8b\", error_in_learning_mode=\"true\"}[$__rate_interval])",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Events passed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cf_e_reporter_app_events_size{reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\", namespace=\"mr-sojern-new-1e325d9-rmp8b\", got_in_queue=\"true\"}[$__rate_interval])",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Events stats of shard - $reporter_shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average processing time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(cf_e_reporter_event_processing_duration_sum{reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\"}[$__rate_interval]) / increase(cf_e_reporter_event_processing_duration_count{reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\"}[$__rate_interval])",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Event rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "reqpm" }
   ],
   "targets": [
    {
     "expr": "increase(cf_e_reporter_event_processing_duration_count{reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\"}[$__rate_interval]) / increase(cf_e_reporter_event_processing_duration_sum{reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\"}[$__rate_interval]) * 60",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Errored events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(error_type) (sum by(reporter_shard) (increase(cf_e_reporter_errored_events{reporter_shard=~\"$reporter_shard\"}[$__rate_interval])))",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Amount of processed events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(cf_e_reporter_event_processing_duration_count{reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\"}[$__rate_interval])",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Cached ignored application events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(reporter_shard) (increase(cf_e_reporter_cached_ignored_events{metric_event_type=\"app\", reporter_shard=~\"$reporter_shard\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached ignored resource events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(reporter_shard) (increase(cf_e_reporter_cached_ignored_events{reporter_shard=~\"$reporter_shard\", metric_event_type=\"resource\"}[$__rate_interval]))",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Performance of shard - $reporter_shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 }
  },
  {
   "title": "Parent app event performance (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cf_e_reporter_event_processing_duration_bucket{metric_event_type=\"parent_app\", reporter_shard=~\"$reporter_shard\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Child app event performance (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cf_e_reporter_event_processing_duration_bucket{metric_event_type=\"child_app\", reporter_shard=~\"$reporter_shard\", cluster=\"managed-runtimes-production\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Resource event performance (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cf_e_reporter_event_processing_duration_bucket{metric_event_type=\"resource\", reporter_shard=~\"$reporter_shard\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Go stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{cluster=\"managed-runtimes-production\", pod=~\"event-reporter-0-x-codefresh-hosted-x-mr-sojern-new--1442d8c480|event-reporter-1-x-codefresh-hosted-x-mr-sojern-new--e57df3c3a8|event-reporter-2-x-codefresh-hosted-x-mr-sojern-new--9b085535c7|event-reporter-3-x-codefresh-hosted-x-mr-sojern-new--c92c4c4beb|event-reporter-4-x-codefresh-hosted-x-mr-sojern-new--ad34f58143\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Amount of go routines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"managed-runtimes-production\", pod=~\"event-reporter-0-x-codefresh-hosted-x-mr-sojern-new--1442d8c480|event-reporter-1-x-codefresh-hosted-x-mr-sojern-new--e57df3c3a8|event-reporter-2-x-codefresh-hosted-x-mr-sojern-new--9b085535c7|event-reporter-3-x-codefresh-hosted-x-mr-sojern-new--c92c4c4beb|event-reporter-4-x-codefresh-hosted-x-mr-sojern-new--ad34f58143\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of OS threads created",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{cluster=\"managed-runtimes-production\", pod=~\"event-reporter-0-x-codefresh-hosted-x-mr-sojern-new--1442d8c480|event-reporter-1-x-codefresh-hosted-x-mr-sojern-new--e57df3c3a8|event-reporter-2-x-codefresh-hosted-x-mr-sojern-new--9b085535c7|event-reporter-3-x-codefresh-hosted-x-mr-sojern-new--c92c4c4beb|event-reporter-4-x-codefresh-hosted-x-mr-sojern-new--ad34f58143\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}