{
 "title": "Codefresh argo-cd events reporter (v2) Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "reporter_shard",
    "label": "Shard number",
    "query": {
     "query": "label_values(cf_e_reporter_queue_size,reporter_shard)"
    }
   },
   {
    "name": "metric_event_type",
    "label": "Metric event type",
    "query": {
     "query": "label_values(cf_e_reporter_event_processing_duration_bucket,metric_event_type)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" }
  ]
 },
 "panels": [
  { "title": "General stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current queue size",
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cf_e_reporter_queue_size{job=\"argo-cd-event-reporter-metrics\"}",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Queue size delta (1m)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cf_e_reporter_queue_size{job=\"argo-cd-event-reporter-metrics\", reporter_shard=~\"$reporter_shard\"}[1m])",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Events stats of shard - $reporter_shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errored events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(error_type) (sum by(reporter_shard) (increase(cf_e_reporter_errored_events{reporter_shard=~\"$reporter_shard\"}[$__rate_interval])))",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Cached ignored application events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(reporter_shard) (increase(cf_e_reporter_cached_ignored_events{metric_event_type=\"app\", reporter_shard=~\"$reporter_shard\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached ignored resource events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(reporter_shard) (increase(cf_e_reporter_cached_ignored_events{reporter_shard=~\"$reporter_shard\", metric_event_type=\"resource\"}[$__rate_interval]))",
     "legendFormat": "{{reporter_shard}}"
    }
   ]
  },
  {
   "title": "Performance of shard - $reporter_shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "Parent app event performance (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cf_e_reporter_event_processing_duration_bucket{metric_event_type=\"parent_app\", reporter_shard=~\"$reporter_shard\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Child app event performance (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cf_e_reporter_event_processing_duration_bucket{job=\"argo-cd-event-reporter-metrics\", metric_event_type=\"child_app\", reporter_shard=~\"$reporter_shard\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Resource event performance (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cf_e_reporter_event_processing_duration_bucket{metric_event_type=\"resource\", reporter_shard=~\"$reporter_shard\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Go stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{source=\"cf-event-reporter\"}"
      }
     ]
    },
    {
     "title": "Amount of go routines",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{source=\"cf-event-reporter\"}"
      }
     ]
    },
    {
     "title": "Number of OS threads created",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{source=\"cf-event-reporter\"}"
      }
     ]
    }
   ]
  }
 ]
}