apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yarik-app-1
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/yaroslav-codefresh/argocd-example-apps.git
    path: helm-guestbook
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: yarik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false
