apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-promotable-app-1
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: promotable-app-1
spec:
  project: default
  source:
    path: product-charts/dev
    repoURL: https://github.com/yaroslav-codefresh/scale-test
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: promotable-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false
