apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: promotion-config
spec:
  applicationSourceSelector:
    matchExpressions:
      - key: app.kubernetes.io/instance
        operator: Exists
  priority: 0
  versionSource:
    file: values.yaml
    jsonPath: $.image.tag
  promotion:
    values.yaml:
      jsonPaths:
        - $.image.tag
