apiVersion: codefresh.io/v1beta1
kind: PromotionTemplate
metadata:
  name: promotion-config
spec:
  applicationSourceSelector:
    matchExpressions:
      - key: app.kubernetes.io/instance
        operator: Exists
  priority: 0
  versionSource:
    file: Chart.yaml
    jsonPath: $.version
  promotion:
    version.yaml:
      jsonPaths:
        - $.version
    Chart.yaml:
      jsonPaths:
        - $.version
        - $.appVersion
    values.yaml:
      jsonPaths:
        - $.image.tag
