{{- range $i := 2 }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.product }}-service-1
  annotations:
    "codefresh.io/product": {{ .Values.spec.product }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: apps-chart
    repoURL: https://github.com/yaroslav-codefresh/scale-test.git
    targetRevision: HEAD
    helm:
      valuesObject:
        spec:
          service: service-1
          product: {{ .Values.spec.product }}
          prod:
            cluster: scale-prod
            path: prod
            repoUrl: https://github.com/oleksandr-codefresh/argo-load-product-{{ $i }}
          dev:
            cluster: scale-test
            path: dev
            repoUrl: https://github.com/oleksandr-codefresh/argo-load-product-{{ $i }}
  destination:
    name: in-cluster
    namespace: {{ .Values.spec.runtimeNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
  {{- end }}
