apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diff-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: ClusterRole
      group: rbac.authorization.k8s.io
      jsonPointers:
        - /rules
  source:
    path: resources/diff-test
    repoURL: https://github.com/yaroslav-codefresh/scale-test
    targetRevision: HEAD
  project: default
  destination:
    name: in-cluster
    namespace: test-diff
